<Project>
  <PropertyGroup>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Sineus Arena</GameDir>
    <BepInExProfile Condition="'$(BepInExProfile)' == ''">$(USERPROFILE)\AppData\Roaming\Thunderstore Mod Manager\DataFolder\SineusArenaSurvivors\profiles\Default</BepInExProfile>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
